<?xml version="1.0" encoding="utf-8"?><Database Name="inventariovisual" Class="DataClasses2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-QDRTM434;Initial Catalog=inventariovisual;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="inventariovisualConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Categoria" Member="Categoria">
    <Type Name="Categoria">
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="categoria" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="Categoria_Producto" Member="Producto" ThisKey="IdCategoria" OtherKey="IdCategoria" Type="Producto" />
    </Type>
  </Table>
  <Table Name="dbo.Producto" Member="Producto">
    <Type Name="Producto">
      <Column Name="IdProducto" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="precio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="categoria" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="stock" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdProveedor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Categoria_Producto" Member="Categoria1" ThisKey="IdCategoria" OtherKey="IdCategoria" Type="Categoria" IsForeignKey="true" />
      <Association Name="Proveedor_Producto" Member="Proveedor" ThisKey="IdProveedor" OtherKey="IdProveedor" Type="Proveedor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Proveedor" Member="Proveedor">
    <Type Name="Proveedor">
      <Column Name="IdProveedor" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="correo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="telefono" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="Proveedor_Producto" Member="Producto" ThisKey="IdProveedor" OtherKey="IdProveedor" Type="Producto" />
    </Type>
  </Table>
</Database>